modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPL"

[[dependencies.hats]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.2,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.hats]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.hats]]
    modId = "architectury"
    mandatory = true
    versionRange = "[9,)"
    ordering = "NONE"
    side = "BOTH"

[[mods]]
    modId = "hats"
    version = "${version}"
    displayName = "Hats"
    description = "Put a hat on it."
    authors = "iChun, guivnf"
    logoFile = "hats.png"

[[mixins]]
    config = "hats.mixins.json"

[[mixins]]
    config = "hats.compat.mixins.json"
