plugins {
    id "dev.architectury.loom" version "${architectury_loom_version}" apply false
    id "architectury-plugin" version "${architectury_plugin_version}"
    id "com.gradleup.shadow" version "8.3.6" apply false
}

architectury {
    minecraft = project.mc_version
}

def mcParts = project.mc_version.split('\\.')
def mcMinor = mcParts.length > 1 ? mcParts[1] : project.mc_version

allprojects {
    group = project.mod_group
    version = "${mcMinor}.${project.mod_version}-mc${project.mc_version}"
}

subprojects {
    apply plugin: "dev.architectury.loom"
    apply plugin: "architectury-plugin"

    base {
        archivesName = "${project.mod_name}"
    }

    repositories {
        maven { url = "https://maven.architectury.dev/" }
        maven { url = "https://maven.neoforged.net/releases" }
        maven { url = "https://maven.fabricmc.net/" }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${project.mc_version}"
        mappings loom.officialMojangMappings()
    }

    java {
        withSourcesJar()
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 21
    }

    processResources {
        inputs.property "version", project.version
        filesMatching("fabric.mod.json") {
            expand "version": project.version
        }
    }
}
