org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G

# Minecraft
mc_version=1.20.1

# Architectury
architectury_plugin_version=3.4-SNAPSHOT
architectury_loom_version=1.6-SNAPSHOT
architectury_version=9.1.12

# Forge
forge_version=47.4.18

# Fabric
fabric_loader_version=0.15.11
fabric_api_version=0.92.0+1.20.1

# Mod
mod_name=Hats
mod_version=11.0.0
mod_id=hats
mod_group=me.guivnf.mods

enabled_platforms=forge,fabric
