pluginManagement {
    repositories {
        maven { url = "https://maven.architectury.dev/" }
        maven { url = "https://maven.neoforged.net/releases" }
        maven { url = "https://maven.fabricmc.net/" }
        gradlePluginPortal()
    }
    plugins {
        id "com.gradleup.shadow" version "8.3.6"
    }
}

rootProject.name = "hats"
include("common", "neoforge", "fabric")
